name: weather scraper
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  git-scraping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4.2.2
        
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2.5.0
        with:
          release: R2025a

      - name: Run MATLAB live script
        uses: matlab-actions/run-command@v2.2.1
        with:
          # Script, function, or statement to execute
          command: scraper

      - name: Commit and push if it changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
            git push      

env:
  OWM_KEY: ${{secrets.OWM_KEY}}
  
